TOP := Demo_top

.PHONY: precheck gds sim

precheck:
	tt-support-tools precheck --info info.yaml --verilog $(TOP).v

gds:
	echo "Skipping real GDS generation (for validation only)"

sim:
	echo "Skipping simulation (not needed for now)"
