TOP := top_twilight_cat

.PHONY: precheck gds sim formal verification

precheck:
	tt-support-tools precheck --info info.yaml --verilog $(TOP).v

gds:
	echo "Skipping real GDS generation (for validation only)"

sim:
	echo "Skipping simulation (for now)"

formal:
	echo "Skipping formal (not used)"

verification:
	echo "Skipping verification (not implemented)"
