name: Run Tiny Tapeout checks

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y make python3-pip
          make install || true  # 你可以先这么写，避免挂掉

      - name: Run precheck
        run: make precheck

      - name: Run simulation
        run: make sim

      - name: Run GDS check
        run: make gds

      - name: Run FPGA test
        run: make fpga
